### ISSUE TITLE
Blog entries not working

### ISSUE THREAD

**Issue by engelhuber** [abachuk/WordPress-jQuery-mobile-and-Phonegap-app-for-iOS#2]
Hi Alex, as I reported on your blog, I uploaded your files on my webspace.
The index is working, but clicking on blog shows nothing except the buttons.
Your example URL and even mine isn't working.
JSON API is installed on my blog.
Any idea?
http://app.windeck24.info/index.html

Thanks and BR
Chris

**Comment by abachuk** [comment]
there are few console errors in your app. The most important one is 
XMLHttpRequest cannot load http://windeck24.info/api/get_recent_posts/. Origin http://app.windeck24.info is not allowed by Access-Control-Allow-Origin.

I think it has to do with subdomain. (app).windeck24.info

**Comment by engelhuber** [comment]
yep, you're right. thats it!
many thanks
